.demo-only{
	background: #f4f6f9;
}

.slds-panel{
	height: 500px; 
	width: 900px
}

.slds-table thead tr{
	background: #e6e6ff;
}

.slds-table tbody tr{
	background: #f4f6f9;
}

.slds-table thead tr th{
	font-weight: bold !important;
	width: 17% !important;
}

.nao-encontrado{
    background: #f4f6f9;
    border-top: 1px solid #d8dde6;
    background-clip: padding-box;
    text-align: center;
    font-weight: bold;
    margin-top: 30px;
    font-size: 14px;
}